### ISSUE TITLE
Problems with Generated `define.go`

### ISSUE THREAD

**Issue by DavePearce** [Consensys/corset#173]
There are a number of issues with the generated `define.go` file.  Here is a rough list, with minimal examples to follow:

- [x] **Formatting**.  The generated `define.go` does not pass `gofmt` (see #191)

- [x] **Unused Variables**.  The generated `define.go` declares variables even when they are not used.  (see #179)

- [x] **More Unused Variables**.  The generated `define.go` still includes variables which are not used.  (see ???)

- [x] **Undefined Variables**.  The generated `define.go` sometimes refers to variables which have not been declared (see #177)

- [x] **Duplicate Variables**.  The generated `define.go` declares variables more than once (see #178). 

- [x] **Mul Arguments**.  The generated `define.go` has `Mul` expressions with more than two arguments (see #203).

@gusiri FYI.
